name: Waydroid Headless (Persistent)

on:
  workflow_dispatch:

jobs:
  waydroid:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      # 1️⃣ Restore previous Waydroid data
      - name: Restore Waydroid Data
        uses: actions/download-artifact@v4
        continue-on-error: true as
        with:
          name: waydroid-data
          path: $HOME/.local/share/waydroid

      # 2️⃣ Install dependencies
      - name: Install Waydroid Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl lxc lxd python3-pip qemu-utils
          sudo systemctl start lxd || true
          sudo lxd waitready || true

      # 3️⃣ Install Waydroid
      - name: Install Waydroid
        run: |
          curl https://repo.waydro.id | sudo bash
          sudo apt install -y waydroid

      # 4️⃣ Initialize Waydroid container if needed
      - name: Initialize Waydroid
        run: |
          if ! waydroid status | grep -q "running"; then
            sudo waydroid init
          fi

      # 5️⃣ Start Waydroid container
      - name: Start Waydroid
        run: |
          sudo waydroid container start
          sudo waydroid session start

      # 6️⃣ Install noVNC to expose GUI
      - name: Setup noVNC
        run: |
          sudo apt install -y novnc websockify x11vnc xvfb
          Xvfb :1 -screen 0 1024x768x16 &
          x11vnc -display :1 -nopw -forever -shared -rfbport 5901 &
          nohup websockify --web=/usr/share/novnc/ 8080 localhost:5901 &

      # 7️⃣ Output connection info
      - name: Show Connection Info
        run: |
          echo "Waydroid GUI available at: http://<runner-ip>:8080"
          echo "VNC port: 5901 (no password)"

      # 8️⃣ Keep the runner alive
      - name: Keep Alive
        run: |
          while true; do
            echo "Waydroid running..."
            sleep 300
          done

      # 9️⃣ Save Waydroid data for next run
      - name: Save Waydroid Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: waydroid-data
          path: $HOME/.local/share/waydroid
